
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import Footer from "../components/StickyFooter"
import TrekNavbar from "../components/TrekNavbar"



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body  className="min-width-[100vh]">
        <div className="">
        <TrekNavbar/>
        </div>
        
        {children}
        <Footer/>
        </body>
    </html>
  );
}
